### PR TITLE
Baryonic feedback

### PR DESCRIPTION
**Pull request by alexander-mead**
Adding the `HMcode-2020` baryonic-feedback model. Thanks to Leila Linke.

### CODE REVIEW

**Comment by alexander-mead** [comment]
I've done some reformatting (minor tidying and style alignment) and changed the names of some of the functions (mainly baryon -> feedback). The larger changes involve only exposing the `hmcode.power()` function and having this take only `T_AGN` as a parameter. This involves some recursive calls to `hmcode.power()`, but I think it's better like this and I think it's nice to not expose the inner workings of the code too much via the function call.

**Comment by alexander-mead** [comment]
It's not quite working yet though...

**Comment by llinke1** [comment]
I have added a test to compare to the Feedback implemented in CAMB. However, I find an issue at small k / large scales - the python implementation suggests a powerspectrum suppression at k<1e-2 h/Mpc. This is similar to https://github.com/cmbant/CAMB/issues/135.
Feedback_Cosmology_0_wo1Hsuppression

**Comment by llinke1** [comment]
I have added the 1-Halo term suppression to the Vanilla halo model. This fixes the issue with the predicted powerspectrum suppression by the baryon feedback at low k. Using 100 random sets of cosmological parameters in a (nu-k-w(a)-CDM)-Model with z<1.5 leads to a mean error: 0.06% std of error: 0.07%, worst error: 0.49%  Feedback_Cosmology_0

**Comment by alexander-mead** [comment]
Okay, great. That's all merged now and I bumped to v1.1.0. Thanks!

One small thing I had to undo: In `hmcode/camb_stuff.py` you had set `WantCls=False` in the `CAMBparams()` function. I don't know why, but doing so changes the model predictions by an annoying amount (say 0.3%). I don't have time to follow this up, but it's probably worth being aware of...

**Pull request merged**
